language: node_js
node_js:
  - 9
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
script: 
  - ENV=PROD yarn build
