language: node_js
node_js:
  - 9
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: build
script: 
  - ENV=PROD yarn build
