export const TEST = 'TEST';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_DESIGNS_TUMBLR = 'GET_DESIGNS_TUMBLR';
export const GET_DESIGNS_BEHANCE = 'GET_DESIGNS_BEHANCE';
